# This workflow tests the script using the latest version of python 3.11
# it run on PR creation and on push to main branch

name: Python script testing using pytest

on:
    pull_request:
        branches: [ main ]
    push:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            # checkout the repo
            - uses: actions/checkout@v2

            # set up python 3.11
            - name: Set up Python 3.11
              uses: actions/setup-python@v2
              with:
                  python-version: 3.11
        
            # install python dependencies      
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            # run pytest
            - name: Run pytest
              run: |
                pytest --log-level=DEBUG -v
