# This workflow tests the script using the latest version of python 3.11
# it run on PR creation and on push to main branch

name: Python script testing using pytest

on:
    pull_request:
        branches: [ main ]
    push:
        branches: [ main ]

env:
    EMAIL_DOMAIN: ${{ vars.EMAIL_DOMAIN }}
    REPO_NAME: ${{ github.event.repository.name }}
    GITHUB_TOKEN: ${{ secrets.PROJECTS_GITHUB_TOKEN }}
     
    PENDING_CHANGES: FALSE
    
    # Load files from the repository variables
    FILES: ${{ vars.FILES }}

    # Load categories from the repository variables
    ALT_LIFESTYLE: ${{ vars.ALT_LIFESTYLE }}
    README: ${{ vars.README }}

    LINES_TO_SKIP: ${{ vars.LINES_TO_SKIP }}

    # testing variables
    ISSUE_NAME: "Test Issue"
    ISSUE_NUMBER: 42
    ISSUE_BODY: "test issue body"
    ISSUE_CREATOR: "test-user"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            # checkout the repo
            - uses: actions/checkout@v3

            # set up python 3.11
            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                  python-version: 3.11
        
            # install python dependencies      
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r scripts/requirements.txt

            # run pytest
            - name: Run pytest
              run: |
                pytest --log-level=DEBUG -v
